### ISSUE TITLE
Tab bar overlaps with window controls

### ISSUE THREAD

**Issue by arinsoye** [nuchi/firefox-quantum-userchromejs#3]
Hi,

It looks like when this is used the window controls overlap with the tab bar and the latter is only partially visible.

I have some other modifications in the userChrome.css file, but they should not be interfering with this.

Is this a known issue? Anyway for me to lower the tab bar a little bit manually when in full screen?

<img width="1346" alt="ss" src="https://user-images.githubusercontent.com/21370488/35464874-3d3d7af8-02ad-11e8-9cb2-c92bc18038a6.png">

**Comment by nuchi** [comment]
Not sure what's causing that. For me, that happens when I move the cursor to the top of the screen:
![screen shot 2018-01-26 at 4 26 06 pm](https://user-images.githubusercontent.com/16771734/35466105-dee58f78-02b5-11e8-9fad-c56cfab3e335.png)

And then when I move the cursor away it reverts to total fullscreen mode:
![screen shot 2018-01-26 at 4 26 25 pm](https://user-images.githubusercontent.com/16771734/35466113-ef170048-02b5-11e8-8967-ff04e6f26def.png)


If I flick the cursor to the top but don't hold it there, I can make just the tab/address bars appear without the system menu bar.
![screen shot 2018-01-26 at 4 25 48 pm](https://user-images.githubusercontent.com/16771734/35466124-ff95d05c-02b5-11e8-87de-5e4cefd6e7b6.png)

(All pictures are of the top-left of the screen.)

If yours is different, I don't know why. Sorry!
